# Generated by Django 4.2.7 on 2023-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_cart_alter_menuitem_image_alter_restaurant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
    ]
