# Generated by Django 4.2.7 on 2023-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='images/doc.jpg', upload_to='restaurant_images/'),
        ),
    ]
