# Generated by Django 4.2.7 on 2023-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_order_orderitem_delete_amount_order_items_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
