# Generated by Django 4.2.7 on 2023-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
